FROM node:16-alpine as builder

WORKDIR /WWW/WWWROOT/

ADD website/package.json /WWW/WWWROOT/

RUN npm install -g npm@8.7.0
RUN npm i

ADD ./website/ /WWW/WWWROOT/
RUN npm run build

FROM nginx

COPY --from=builder WWW/WWWROOT/dist/ /usr/share/nginx/html/
WORKDIR /WWW/WWWROOT/
EXPOSE 80
# COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf